GGAtest:
	g++-6 -o GGATest.exe GGATest.cpp ../../cores/Senscape.cpp ../../cores/SensorClient.h ../../../GPS/GPS.cpp -fpermissive -I ../../cores/ -I ../../../GPS/

RMCtest:
	g++-6 -o RMCTest.exe RMCTest.cpp ../../cores/Senscape.cpp ../../cores/SensorClient.h ../../../GPS/GPS.cpp -fpermissive -I ../../cores/ -I ../../../GPS/
